# Generated by Django 3.2.5 on 2021-07-30 17:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0004_curso_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('celular', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.curso')),
            ],
            options={
                'verbose_name': 'Interesado',
                'verbose_name_plural': 'Interesados',
                'db_table': 'interesado',
                'ordering': ['-updated_at'],
            },
        ),
    ]
