# Generated by Django 3.2.5 on 2021-07-30 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interesado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesado',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
