# Generated by Django 3.2.5 on 2021-07-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leccion',
            name='unidad',
        ),
        migrations.AddField(
            model_name='unidad',
            name='lecciones',
            field=models.ManyToManyField(to='curso.Leccion'),
        ),
        migrations.AlterModelTable(
            name='curso',
            table='curso',
        ),
        migrations.AlterModelTable(
            name='leccion',
            table='leccion',
        ),
        migrations.AlterModelTable(
            name='unidad',
            table='unidad',
        ),
    ]
