# Generated by Django 3.2.5 on 2021-07-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_beneficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficio',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
