# Generated by Django 3.2.5 on 2021-08-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210801_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default='asdfasdf', max_length=30),
            preserve_default=False,
        ),
    ]
