# Generated by Django 3.2.5 on 2021-08-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
